spring:
  mail:
    host: e-mail.uni-passau.de
    port: 587
    username: <name>
    password: <pass>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000